### ISSUE TITLE
Add elevation to round icon button on home page

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#12]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Add some elevation to the round icon button on the home page. These buttons are used in the `HOURS PER DAY` and `EXPERIENCE` money cards.

**Comment by Harshs0891** [comment]
@superiorsd10 I wants to work on this issue plz assign this to me.
Thank You

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! All the best!
