### ISSUE TITLE
Center the your results text and style it

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#13]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Center the "YOUR RESULTS" text horizontally, and add some stroke width, and stroke color to it.

**Comment by Harshs0891** [comment]
@superiorsd10 I wants to work on this issue plz assign this to me.
Thank You

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! All the best!

**Comment by Harshs0891** [comment]
Thank You Sir
