### ISSUE TITLE
Add padding to the bottom button on results page

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#14]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Add some padding to the bottom button (RE-CALCULATE) on the results page keeping in mind the responsiveness.

**Comment by Dinokojt7** [comment]
Assign me this issue.

**Comment by superiorsd10** [comment]
Sure @Dinokojt7 ! I'm assigning this to you. Make a new branch from the main, and start working on the issue.

**Comment by Dinokojt7** [comment]
I'm working on it. The padding you want, should it be similar to the padding applied on the calculate button from instructions page?

**Comment by superiorsd10** [comment]
> I'm working on it. The padding you want, should it be similar to the padding applied on the calculate button from instructions page? 
> 

Yes, to maintain the aesthetics of the app.

**Comment by superiorsd10** [comment]
@Dinokojt7 Are you working on this issue? If not, I'll assign it to someone else.

**Comment by Dinokojt7** [comment]
Seeing that you've used a container to design this button, its height falls outside the scope of providing it with padding but remains a very key part of the required aesthetics so the button won't look completely like the calculate button on the instructions page. 

If we are to go specifically for a similar look we have to apply the responsive parameters and assign a responsive value of screenWidth / 8, which is what I ended up doing. The other solution is to use the same component i.e forgo the custom button made from a container and opt for the elevated button.

**Comment by superiorsd10** [comment]
Sorry for the confusion but you're from outside this organization, and these issues are made for the freshers so that they can get an overview of open-source. So I'm unassigning you. Thank you! @Dinokojt7

**Comment by Dinokojt7** [comment]
Wait lol I've done some decent work on it please review my pull request I didn't mean any harm, also I'd love to work on some of the other issues

**Comment by superiorsd10** [comment]
Okay, I'll. But please don't work on any other issues, as they are for the students of our university. It's part of an event. @Dinokojt7

**Comment by Dinokojt7** [comment]
I understand sorry for that, but I would truly appreciate some review on what I've worked on if you may, and since we had already started on a good note I think it would be awesome if we end it accordingly. I, however, see that I cannot push to origin HEAD are you able to advise on that?

**Comment by superiorsd10** [comment]
Okay @Dinokojt7 , you can make a PR!

**Comment by Dinokojt7** [comment]
Okay @superiorsd10 I have made a push to new branch thank you

**Comment by superiorsd10** [comment]
@Dinokojt7 You haven't made any PR!

**Comment by ADudhe01** [comment]
@superiorsd10 Could you please assign this issue to me

**Comment by superiorsd10** [comment]
Sure @ADudhe01 ! All the best!
