### ISSUE TITLE
Change the loading text of Splash Screen

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#2]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description
You've to replace the loading text of the Splash Screen i.e. LOADING... with something of your choice.

**Comment by Dis1309** [comment]
hi @superiorsd10  i would like to work on this issue. please assign it to me

**Comment by superiorsd10** [comment]
Sure @Dis1309 ! All the best!
