### ISSUE TITLE
Remove the debug banner

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#4]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Remove the debug banner visible at the top right corner of the screen.

**Comment by Dis1309** [comment]
hi @superiorsd10 i would like to work on this issue. please assign it to me

**Comment by superiorsd10** [comment]
@Dis1309 Good to see your enthusiasm! But first, make a PR for the two issues that are assigned to you. Then I'll assign this to you.
