### ISSUE TITLE
Center the instructions page vertically

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#5]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Make the instruction title, instructions, and CALCULATE button appear at the vertical center.

**Comment by Dis1309** [comment]
hi @superiorsd10 i am interested in this issue please assign it to me

**Comment by superiorsd10** [comment]
Sure @Dis1309 ! All the best!
