### ISSUE TITLE
Add border radius to calculate button on Instructions page

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#7]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Add border-radius to the `CALCULATE` button on the Instructions Page.

**Comment by Harshs0891** [comment]
@superiorsd10 plz assign me this issue i wants to work on it

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! Go ahead!
