### ISSUE TITLE
Center the app bar title

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#8]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Center the app bar title i.e. `IT'S MONEY` on the home page and results page.

**Comment by Harshs0891** [comment]
@superiorsd10 Plz assign this to me i wants to work on it.
Thank you

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! All the best!
