### ISSUE TITLE
Change the CP and DEV image on money card

### ISSUE THREAD

**Issue by superiorsd10** [iiitl/its-money#9]
Read the [contribution guidelines](https://github.com/iiitl/its-money/blob/main/CONTRIBUTING.md) and [readme](https://github.com/iiitl/its-money/blob/main/README.md). Ask to get assigned this issue.

### Description

Change the CP and DEV images on the money card. You can place any images of your choice. It should maintain the aesthetics and responsiveness of the app.

**Comment by Harshs0891** [comment]
@superiorsd10 I wants to work on this issue . Please assign me this issue.
Thank You!

**Comment by superiorsd10** [comment]
Sure @Harshs0891 ! All the best!
